// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkazgwdjamqlqvkpjizc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrYXpnd2RqYW1xbHF2a3BqaXpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjQ2OTUsImV4cCI6MjA2NTUwMDY5NX0.GPt5uFuGjp5c1HuvfXzoZXRyHCuPzuKklOCQH4s1J3I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);